In [41]:
import numpy as np

In [7]:
np.__version__ # to check version of numpy

'1.23.5'

In [8]:
print(np.__doc__) # to see some documentation of numpy


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

In [9]:
# why numpy
# -methemathical function
# faster

In [10]:
# example 1

In [11]:
l =[1,23,4,5,6] 

In [12]:
l

[1, 23, 4, 5, 6]

In [13]:
arr =np.array(l) # to convert list into array

In [14]:
arr

array([ 1, 23,  4,  5,  6])

In [15]:
type(np.array(l))  # to check type

numpy.ndarray

In [16]:
arr.ndim # to check dimensions of array

1

In [17]:
# example 2

In [18]:
l2=[1,2,3,4,5,6,'Abhinesh']
arr1=np.array(l2)
arr1


array(['1', '2', '3', '4', '5', '6', 'Abhinesh'], dtype='<U21')

In [19]:
# two Dimensions array in numpy

In [20]:
arr2=np.array([[1,2,3],[4,5,6]])   # to create 2D array

In [21]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr2.ndim

2

In [23]:
# another method to create array in numpy

In [24]:
# 1D Array

In [25]:
x =np.arange(2,6).reshape(4)

In [26]:
x

array([2, 3, 4, 5])

In [27]:
x.ndim

1

In [28]:
# 2d Array 

In [29]:
x1 = np.arange(2,10).reshape(2,4)

In [30]:
x1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [31]:
# 3D array

In [32]:
x2 = np.arange(24).reshape(4,3,2)

In [33]:
x2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [34]:
l=[1,2,3,4]

In [35]:
np.array(l)

array([1, 2, 3, 4])

In [36]:
np.matrix(l) # when we cretae matrix it's form array like object 
              # but  be-defaults  matrix will be  2D

matrix([[1, 2, 3, 4]])

In [37]:
# matrix always is by defaults 2D

In [38]:
np.matrix([[[1,3],[2,4],[7,8]]]) 

ValueError: matrix must be 2-dimensional

In [39]:
# Above we create 3D matrix but it's give error 
# matrix must be 2-dimensional
# it means matrix is only and only 2D

In [40]:
np.array([[[1,3],[2,4],[7,8]]]) 

array([[[1, 3],
        [2, 4],
        [7, 8]]])

In [41]:
# but array having 3D as we create above

In [42]:
# more way to covert to array

In [43]:
np.asarray([[[1,3],[2,4],[7,8]]]) 

array([[[1, 3],
        [2, 4],
        [7, 8]]])

In [44]:
np.asanyarray([[[1,3],[2,4],[7,8]]]) #Convert the input to an ndarray, but pass ndarray subclasses through

array([[[1, 3],
        [2, 4],
        [7, 8]]])

In [45]:
# example

In [46]:
mat=np.matrix(l)

In [47]:
mat

matrix([[1, 2, 3, 4]])

In [48]:
np.asanyarray(mat) # it is not covert in array . it is still matrix

matrix([[1, 2, 3, 4]])

In [49]:
# covert tuple to array

In [50]:
t =([1,2,3],[4,5,6])

In [51]:
type(t)

tuple

In [52]:
np.asanyarray(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
a=5
np.array(a)

array(5)

In [54]:
# shallow copy 


In [63]:
#A shallow copy creates a new object with references to the 
#same elements as the original.

In [64]:
l3 =[1,2,3,4,5]

In [65]:
l3

[1, 2, 3, 4, 5]

In [66]:
arr4 = np.array(l)

In [67]:
arr4

array([1, 2, 3, 4])

In [68]:
a=arr4

In [69]:
a[0]

1

In [70]:
arr4[0]= 1000

In [87]:
arr4

array([1000,    2,    3,    4])

In [73]:
a

array([1000,    2,    3,    4])

In [74]:
# in this shallow copy when we create a array --arr[1,3,4,54]
#then in OS a memory is created 
#  and if a=arr
# then a and arr are reflected to same memory location 
# this Concept is known as shallow copy.

In [75]:
# deep copy

In [78]:
#A shallow copy creates a new object with references to the 
#same elements as the original.

In [79]:
b =a.copy()

In [80]:
b

array([1000,    2,    3,    4])

In [81]:
b[0]=123

In [82]:
b

array([123,   2,   3,   4])

In [94]:
a

array([1000,    2,    3,    4])

In [84]:
# there are multiple ways to Generating arrays

In [ ]:
np.fromfunction(lambda i,j: i==j,shape=(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [89]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
arr2.shape

(2, 3)

In [95]:
arr1.size

7

In [96]:
arr2.size

6

In [97]:
np.fromfunction(lambda i,j: i==j,shape=(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [98]:
np.fromfunction(lambda i,j: i*j,shape=(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [99]:
np.fromfunction(lambda i,j: i-j,shape=(3,3))

array([[ 0., -1., -2.],
       [ 1.,  0., -1.],
       [ 2.,  1.,  0.]])

In [100]:
np.fromfunction(lambda i,j: i+j,shape=(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [101]:
np.fromfunction(lambda i,j: i/j,shape=(3,3))

/tmp/ipykernel_102/1876743146.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda i,j: i/j,shape=(3,3))
/tmp/ipykernel_102/1876743146.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda i,j: i/j,shape=(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [102]:
np.fromfunction(lambda i,j: i!=j,shape=(3,3))

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [117]:
iterable=(i*i for i in range (5))

In [118]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [116]:
np .fromstring("23 2 3 4 5 6",sep=" ")

array([23.,  2.,  3.,  4.,  5.,  6.])

In [120]:
arr2.dtype

dtype('int64')

In [123]:
lists =[1,2,3]
arr= np.array(lists)
arr.dtype

dtype('int64')

In [124]:
list(range(5))

[0, 1, 2, 3, 4]

In [125]:
range(5)

range(0, 5)

In [127]:
list(range(1.0,2.10)) # range can't define with float value

TypeError: 'float' object cannot be interpreted as an integer

In [130]:
np.arange(0.1,10.2,0.2)

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,
        2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,
        8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1])

In [133]:
list(np.arange(0.1,10.2,0.5))

[0.1,
 0.6,
 1.1,
 1.6,
 2.1,
 2.6,
 3.1,
 3.6,
 4.1,
 4.6,
 5.1,
 5.6,
 6.1,
 6.6,
 7.1,
 7.6,
 8.1,
 8.6,
 9.1,
 9.6,
 10.1]

In [4]:
np.linspace(1,5,100)# 

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [9]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [10]:
np.logspace(1,5,10,base=10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [36]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
a=np.zeros((3,4))

In [38]:
a.ndim

2

In [39]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
b=np.zeros((3,3,4))

In [62]:
b

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [55]:
b.ndim

3

In [51]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [63]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
add=np.ones((1,4,3,4))

In [70]:
add+5

array([[[[11., 11., 11., 11.],
         [11., 11., 11., 11.],
         [11., 11., 11., 11.]],

        [[11., 11., 11., 11.],
         [11., 11., 11., 11.],
         [11., 11., 11., 11.]],

        [[11., 11., 11., 11.],
         [11., 11., 11., 11.],
         [11., 11., 11., 11.]],

        [[11., 11., 11., 11.],
         [11., 11., 11., 11.],
         [11., 11., 11., 11.]]]])

In [73]:
add+5*2

array([[[[11., 11., 11., 11.],
         [11., 11., 11., 11.],
         [11., 11., 11., 11.]],

        [[11., 11., 11., 11.],
         [11., 11., 11., 11.],
         [11., 11., 11., 11.]],

        [[11., 11., 11., 11.],
         [11., 11., 11., 11.],
         [11., 11., 11., 11.]],

        [[11., 11., 11., 11.],
         [11., 11., 11., 11.],
         [11., 11., 11., 11.]]]])