In [1]:
import numpy as np

In [2]:
arr =np.ones((3,4))

In [3]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [5]:
np.empty((3,4),int)
#Return a new array of given shape and type, without initializing entries.\
# it give random value 


array([[4618441417868443648, 4618441417868443648, 4618441417868443648,
        4618441417868443648],
       [4618441417868443648, 4618441417868443648, 4618441417868443648,
        4618441417868443648],
       [4618441417868443648, 4618441417868443648, 4618441417868443648,
        4618441417868443648]])

In [6]:
np.empty((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [7]:
np.empty((2,4))

array([[4.65502575e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [8]:
np.eye(5 ,dtype=int)# it give always n*n
# Return a 2-D array with ones on the diagonal and zeros elsewhere.
# its always give you a Square matrix 
# to calculate inverse of matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [9]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
import pandas as pd

In [11]:
pd.DataFrame(arr)# here we covert array into dataframe

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [12]:
 # extra topic
import random #it is a module in python

In [13]:
random.choice((1,2,3,4,5,6))

5

In [14]:
# above random.choice when we execute it every time
# it gives different different output

In [15]:
random.choice("Abhinesh")

'h'

In [16]:
random.randrange(1,15) # here random give data betweem 1 to 15

6

In [17]:
random.random() # it give random data between 0 and 1

0.503767312740292

In [18]:
lists=[1,2,3,4,5]
random.shuffle(lists)

In [19]:
lists

[3, 2, 1, 5, 4]

In [20]:
random.uniform(7,14)

9.568389976858203

In [21]:
# random data given also by numpy but it is not use random library’s 

In [22]:
np.random.rand(2,3) # random value generated in this array

array([[0.91572925, 0.39781749, 0.01635511],
       [0.56404144, 0.49804859, 0.60515886]])

In [23]:
np.random.rand(1)


array([0.79363454])

In [24]:
a

NameError: name 'a' is not defined

In [ ]:
np.random.rand(2,3)

In [25]:
np.random.randn(2,3) # it is random normal distribution 

array([[-0.29546888, -1.05009144, -1.7224637 ],
       [ 1.24346224,  0.42309525,  0.21531171]])

In [26]:
np.random.random_sample() # it gives random data between 0 and 1

0.42675315993343954

In [27]:
np.random.randint(1,5,size=(3,4))

array([[1, 3, 2, 3],
       [3, 3, 1, 4],
       [2, 2, 4, 2]])

In [28]:
arr=np.random.randint(2,5,size=(2,3))

In [29]:
arr

array([[3, 4, 3],
       [4, 3, 2]])

In [30]:
arr.size


6

In [31]:
arr.shape

(2, 3)

In [32]:
arr.ndim

2

In [33]:
arr.reshape(1,6)

array([[3, 4, 3, 4, 3, 2]])

In [34]:
arrr=np.random.randint(1,9 , size=(6,4))

In [35]:
arrr


array([[4, 2, 1, 4],
       [4, 8, 5, 8],
       [3, 5, 2, 1],
       [3, 4, 6, 8],
       [6, 7, 3, 5],
       [1, 2, 5, 1]])

In [36]:
arrr.size

24

In [37]:
arrr.reshape(4,6)

array([[4, 2, 1, 4, 4, 8],
       [5, 8, 3, 5, 2, 1],
       [3, 4, 6, 8, 6, 7],
       [3, 5, 1, 2, 5, 1]])

In [38]:
arrr.reshape(3,8)

array([[4, 2, 1, 4, 4, 8, 5, 8],
       [3, 5, 2, 1, 3, 4, 6, 8],
       [6, 7, 3, 5, 1, 2, 5, 1]])

In [39]:
arrr.reshape(12,2)

array([[4, 2],
       [1, 4],
       [4, 8],
       [5, 8],
       [3, 5],
       [2, 1],
       [3, 4],
       [6, 8],
       [6, 7],
       [3, 5],
       [1, 2],
       [5, 1]])

In [40]:
arrr.reshape(2,12)

array([[4, 2, 1, 4, 4, 8, 5, 8, 3, 5, 2, 1],
       [3, 4, 6, 8, 6, 7, 3, 5, 1, 2, 5, 1]])

In [41]:
arr.reshape(2,-1)

array([[3, 4, 3],
       [4, 3, 2]])

In [42]:
arrr.reshape(6,-1)

array([[4, 2, 1, 4],
       [4, 8, 5, 8],
       [3, 5, 2, 1],
       [3, 4, 6, 8],
       [6, 7, 3, 5],
       [1, 2, 5, 1]])

In [43]:
arrr.reshape(-1,6)

array([[4, 2, 1, 4, 4, 8],
       [5, 8, 3, 5, 2, 1],
       [3, 4, 6, 8, 6, 7],
       [3, 5, 1, 2, 5, 1]])

In [44]:
arrr.reshape(3,8).base

array([[4, 2, 1, 4],
       [4, 8, 5, 8],
       [3, 5, 2, 1],
       [3, 4, 6, 8],
       [6, 7, 3, 5],
       [1, 2, 5, 1]])

In [45]:
arrr.reshape(6,4)

array([[4, 2, 1, 4],
       [4, 8, 5, 8],
       [3, 5, 2, 1],
       [3, 4, 6, 8],
       [6, 7, 3, 5],
       [1, 2, 5, 1]])

In [46]:
arrr.reshape(3,8).base

array([[4, 2, 1, 4],
       [4, 8, 5, 8],
       [3, 5, 2, 1],
       [3, 4, 6, 8],
       [6, 7, 3, 5],
       [1, 2, 5, 1]])

In [47]:
arrr.reshape(12,2).base

array([[4, 2, 1, 4],
       [4, 8, 5, 8],
       [3, 5, 2, 1],
       [3, 4, 6, 8],
       [6, 7, 3, 5],
       [1, 2, 5, 1]])

In [48]:
# .base retrieves the base object of the reshaped array.
# The .base attribute in NumPy is used to access the original object that 
# shares the same data. If the array is a view of another array, .base 
# returns that original array; otherwise, it returns None.

In [49]:
arrr.reshape(2,4,3)

array([[[4, 2, 1],
        [4, 4, 8],
        [5, 8, 3],
        [5, 2, 1]],

       [[3, 4, 6],
        [8, 6, 7],
        [3, 5, 1],
        [2, 5, 1]]])

In [50]:
arrr.ndim

2

In [51]:
new_arr=np.random.randint(1,9,size=(2,3,4))

In [52]:
new_arr

array([[[6, 1, 7, 3],
        [3, 4, 6, 4],
        [2, 8, 3, 4]],

       [[2, 6, 7, 2],
        [5, 5, 5, 8],
        [4, 6, 8, 4]]])

In [53]:
new_arr.reshape(2,6,2)

array([[[6, 1],
        [7, 3],
        [3, 4],
        [6, 4],
        [2, 8],
        [3, 4]],

       [[2, 6],
        [7, 2],
        [5, 5],
        [5, 8],
        [4, 6],
        [8, 4]]])

In [54]:
new_arr.reshape(2,4,3)

array([[[6, 1, 7],
        [3, 3, 4],
        [6, 4, 2],
        [8, 3, 4]],

       [[2, 6, 7],
        [2, 5, 5],
        [5, 8, 4],
        [6, 8, 4]]])

In [55]:
new_arr.reshape(2,2,3,2)

array([[[[6, 1],
         [7, 3],
         [3, 4]],

        [[6, 4],
         [2, 8],
         [3, 4]]],


       [[[2, 6],
         [7, 2],
         [5, 5]],

        [[5, 8],
         [4, 6],
         [8, 4]]]])

In [56]:
arr1=np.random.randint(1,10,(5,6))

In [57]:
arr1

array([[1, 9, 4, 9, 6, 8],
       [6, 6, 9, 4, 6, 3],
       [4, 1, 5, 3, 8, 9],
       [2, 9, 7, 3, 8, 5],
       [4, 3, 7, 6, 7, 6]])

In [58]:
arr1>5 # use for filter
       #it give true false accoding to condition


array([[False,  True, False,  True,  True,  True],
       [ True,  True,  True, False,  True, False],
       [False, False, False, False,  True,  True],
       [False,  True,  True, False,  True, False],
       [False, False,  True,  True,  True,  True]])

In [59]:
arr1[arr1>5] # use for filter
            # it give me all the value in array where condition is true

array([9, 9, 6, 8, 6, 6, 9, 6, 8, 9, 9, 7, 8, 7, 6, 7, 6])

In [60]:
arr1[arr1 < 5]

array([1, 4, 4, 3, 4, 1, 3, 2, 3, 4, 3])

In [62]:
arr1

array([[1, 9, 4, 9, 6, 8],
       [6, 6, 9, 4, 6, 3],
       [4, 1, 5, 3, 8, 9],
       [2, 9, 7, 3, 8, 5],
       [4, 3, 7, 6, 7, 6]])

In [70]:
arr1[0] # for aceess a particular row

array([1, 9, 4, 9, 6, 8])

In [71]:
arr1[3][1] # for access a particular element

9

In [72]:
arr1

array([[1, 9, 4, 9, 6, 8],
       [6, 6, 9, 4, 6, 3],
       [4, 1, 5, 3, 8, 9],
       [2, 9, 7, 3, 8, 5],
       [4, 3, 7, 6, 7, 6]])

In [79]:
# for access a particular column
arr1[0 , [1,3]]

array([9, 9])

In [80]:
arr1[2:4]

array([[4, 1, 5, 3, 8, 9],
       [2, 9, 7, 3, 8, 5]])

In [81]:
arr1[2:5]

array([[4, 1, 5, 3, 8, 9],
       [2, 9, 7, 3, 8, 5],
       [4, 3, 7, 6, 7, 6]])

In [86]:
arr1[2:4,[0,2]]

array([[4, 5],
       [2, 7]])

In [87]:
arr1

array([[1, 9, 4, 9, 6, 8],
       [6, 6, 9, 4, 6, 3],
       [4, 1, 5, 3, 8, 9],
       [2, 9, 7, 3, 8, 5],
       [4, 3, 7, 6, 7, 6]])

In [88]:
arr1[0]

array([1, 9, 4, 9, 6, 8])

In [89]:
arr1[2:5, 0:2] # slicing

array([[4, 1],
       [2, 9],
       [4, 3]])

In [92]:
arr1[2,2:5]

array([5, 3, 8])

In [93]:
arr1[[2,4],[0,2]]

array([4, 7])

In [96]:
arr1[[3,4],[4,4]] # select specific row of data

array([8, 7])

In [100]:
arr1[[2,4]]# selecting specific column

array([[4, 1, 5, 3, 8, 9],
       [4, 3, 7, 6, 7, 6]])

In [101]:
arr1[2:4] # slicing

array([[4, 1, 5, 3, 8, 9],
       [2, 9, 7, 3, 8, 5]])

In [108]:
# add ,sub, multi, divide two array

In [109]:
arr2 =np.random.randint(1,3, (3,3))
arr3 =np.random.randint(1,3, (3,3))

In [110]:
arr2

array([[1, 1, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [111]:
arr3

array([[2, 2, 2],
       [1, 1, 2],
       [1, 2, 1]])

In [112]:
arr2+arr3

array([[3, 3, 3],
       [3, 2, 3],
       [3, 4, 3]])

In [113]:
arr2-arr3

array([[-1, -1, -1],
       [ 1,  0, -1],
       [ 1,  0,  1]])

In [114]:
arr2*arr3

array([[2, 2, 2],
       [2, 1, 2],
       [2, 4, 2]])

In [115]:
arr2/arr3

array([[0.5, 0.5, 0.5],
       [2. , 1. , 0.5],
       [2. , 1. , 2. ]])

In [116]:
# this is index wise add , sub , multi, div

In [117]:
# matrix multiplication

In [118]:
arr2

array([[1, 1, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [119]:
arr3

array([[2, 2, 2],
       [1, 1, 2],
       [1, 2, 1]])

In [121]:
arr2 @ arr3  # matrix multiplication



array([[ 4,  5,  5],
       [ 6,  7,  7],
       [ 8, 10, 10]])

In [129]:
# 1--> M x N     2-->  P x Q   if N=P then it will multiple

In [130]:
arr4=np.random.randint(1,3,(3,4))

In [131]:
arr5=np.random.randint(1,3,(4,5))

In [132]:
arr4

array([[1, 1, 1, 2],
       [1, 1, 1, 1],
       [2, 2, 2, 1]])

In [133]:
arr5

array([[1, 2, 1, 1, 2],
       [2, 1, 2, 2, 1],
       [1, 1, 1, 1, 1],
       [1, 2, 2, 1, 2]])

In [134]:
arr4 @ arr5

array([[ 6,  8,  8,  6,  8],
       [ 5,  6,  6,  5,  6],
       [ 9, 10, 10,  9, 10]])

In [135]:
arr1

array([[1, 9, 4, 9, 6, 8],
       [6, 6, 9, 4, 6, 3],
       [4, 1, 5, 3, 8, 9],
       [2, 9, 7, 3, 8, 5],
       [4, 3, 7, 6, 7, 6]])

In [136]:
arr1/0

/tmp/ipykernel_78/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])