In [40]:
import numpy as np

In [41]:
# Broad Casting
'''In NumPy, broadcasting is a powerful mechanism that
allows you to perform operations on arrays of different 
shapes and sizes. Broadcasting automatically aligns 
arrays with compatible shapes during arithmetic 
operations, making it unnecessary to explicitly reshape
or tile arrays.
'''



'In NumPy, broadcasting is a powerful mechanism that\nallows you to perform operations on arrays of different \nshapes and sizes. Broadcasting automatically aligns \narrays with compatible shapes during arithmetic \noperations, making it unnecessary to explicitly reshape\nor tile arrays.\n'

In [42]:
arr =np.zeros((3,4))

In [43]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
arr+1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [46]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
a =np.array([1,2,3,4])

In [48]:
a

array([1, 2, 3, 4])

In [49]:
result = arr +a

In [50]:
result

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [51]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
b=np.array([[1,2,3]])

In [53]:
# transpose 

In [54]:
b

array([[1, 2, 3]])

In [55]:
b.T   # transpose 

array([[1],
       [2],
       [3]])

In [56]:
b

array([[1, 2, 3]])

In [57]:
arr +b 

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [58]:
b.T

array([[1],
       [2],
       [3]])

In [59]:
arr + b.T    # for add row wise

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [61]:
c = np.array([[2],[5],[6]])

In [62]:
c

array([[2],
       [5],
       [6]])

In [63]:
arr+c

array([[2., 2., 2., 2.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.]])

In [64]:
# for Functions 

In [66]:
arr1 =np.random.randint(1,3,(3,3))

In [67]:
arr1

array([[1, 2, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [68]:
np.sqrt(arr1) # for square root

array([[1.        , 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356]])

In [69]:
np.log10(arr1)  # for log data

array([[0.     , 0.30103, 0.     ],
       [0.30103, 0.     , 0.     ],
       [0.30103, 0.30103, 0.30103]])

In [71]:
np.exp(arr1) # for exponential 

array([[2.71828183, 7.3890561 , 2.71828183],
       [7.3890561 , 2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 , 7.3890561 ]])

In [74]:
arr2 = np.array([1 ,2,3])

In [75]:
arr2

array([1, 2, 3])

In [76]:
np.min(arr2) # to find minimum 

1

In [78]:
np.max(arr2)  # to find  Maximum 

3

In [79]:
arr1

array([[1, 2, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [80]:
np.min(arr1)

1

In [81]:
np.max(arr1)

2

In [82]:
arr1


array([[1, 2, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [84]:
arr1.T # for Transpose 



array([[1, 2, 2],
       [2, 1, 2],
       [1, 1, 2]])

In [93]:
arr1

array([[1, 2, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [94]:
arr1.flatten() # reduce higher dimension to one dimension 

array([1, 2, 1, 2, 1, 1, 2, 2, 2])

In [104]:
arr4 =np.array([[1,2,3],[4,5,6],[1,2,3]])

In [105]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
np.sum(arr4)

27

In [107]:
np.sum(arr4 ,axis =0)  # it calculating row  wise

array([ 6,  9, 12])

In [109]:
np.sum(arr4 ,axis =1)   # it calculating column  wise

array([ 6, 15,  6])

In [110]:
# Expand  Dimension --- increase the dimensions 

In [111]:
# this Function expand the array by inserting a new axis

In [112]:
arr5 =np.array([1,2,3,4])

In [113]:
arr5

array([1, 2, 3, 4])

In [114]:
arr5.ndim

1

In [119]:
arr6=np.expand_dims(arr5 ,axis =0)

In [120]:
arr6

array([[1, 2, 3, 4]])

In [121]:
arr6=np.expand_dims(arr5 ,axis =1)

In [122]:
arr6

array([[1],
       [2],
       [3],
       [4]])

In [123]:
arr8 =np.zeros((3,4))

In [124]:
arr8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [126]:
arr9=np.expand_dims(arr8 ,axis =0)

In [127]:
arr9

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])