In [43]:
import numpy as np

In [44]:
# squeeze function : It is reduce  one dimensions of any 2D or any Dimensions 

In [45]:
data =np.array([[1],[2],[3]])

In [46]:
data

array([[1],
       [2],
       [3]])

In [47]:
data.ndim

2

In [48]:
a=np.squeeze(data)

In [49]:
a.ndim

1

In [50]:
# repeat Function : it is use for repeating data and its output is always in one dimension 

In [51]:
data

array([[1],
       [2],
       [3]])

In [52]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [53]:
arr =np.random.randint(1,9 ,(3,3))

In [54]:
arr

array([[2, 4, 2],
       [8, 1, 1],
       [3, 8, 5]])

In [55]:
np.repeat(arr,2)

array([2, 2, 4, 4, 2, 2, 8, 8, 1, 1, 1, 1, 3, 3, 8, 8, 5, 5])

In [56]:
np.repeat(arr ,2 , axis=1)

array([[2, 2, 4, 4, 2, 2],
       [8, 8, 1, 1, 1, 1],
       [3, 3, 8, 8, 5, 5]])

In [57]:
np.repeat(arr ,2 , axis=0)

array([[2, 4, 2],
       [2, 4, 2],
       [8, 1, 1],
       [8, 1, 1],
       [3, 8, 5],
       [3, 8, 5]])

In [58]:
# roll function :In NumPy, the numpy.roll function is used to shift the
# elements of an array along a specified axis.

#numpy.roll in NumPy helps shift array elements in a circular manner along
#a chosen axis, like rolling a wheel, bringing elements that reach the end 
#back to the start.



In [59]:
c=np.array([[1],[2],[3]])

In [60]:
c

array([[1],
       [2],
       [3]])

In [61]:
np.roll(c ,1)

array([[3],
       [1],
       [2]])

In [62]:
np.roll(c ,shift=2)

array([[2],
       [3],
       [1]])

In [63]:
np.roll(c,-1)

array([[2],
       [3],
       [1]])

In [64]:
import numpy as np

# Create a sample array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Roll the elements to the right along the flattened array
rolled_array = np.roll(arr, shift=2)

print("Original array:")
print(arr)

print("\nRolled array:")
print(rolled_array)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rolled array:
[[8 9 1]
 [2 3 4]
 [5 6 7]]


In [65]:
# to print any data in diagonally . which data you inserting  or pass into diagonal 

In [66]:
d=np.diag(np.array([1,2,3,4,5]))

In [67]:
d

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [68]:
np.roll(d,1)

array([[5, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [69]:
# Binary Operation on array

In [70]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))


In [71]:
arr1

array([[2, 4, 3, 5],
       [5, 4, 9, 9],
       [3, 7, 2, 1]])

In [72]:
arr2

array([[9, 2, 3, 2],
       [4, 3, 4, 7],
       [4, 5, 2, 5]])

In [73]:
arr1+arr2

array([[11,  6,  6,  7],
       [ 9,  7, 13, 16],
       [ 7, 12,  4,  6]])

In [74]:
arr1 

array([[2, 4, 3, 5],
       [5, 4, 9, 9],
       [3, 7, 2, 1]])

In [75]:
~arr1  # for negation 

array([[ -3,  -5,  -4,  -6],
       [ -6,  -5, -10, -10],
       [ -4,  -8,  -3,  -2]])

In [76]:
arr1 **arr1

array([[        4,       256,        27,      3125],
       [     3125,       256, 387420489, 387420489],
       [       27,    823543,         4,         1]])

In [77]:
arr1

array([[2, 4, 3, 5],
       [5, 4, 9, 9],
       [3, 7, 2, 1]])

In [78]:
arr2

array([[9, 2, 3, 2],
       [4, 3, 4, 7],
       [4, 5, 2, 5]])

In [83]:
arr1**arr2

array([[    512,      16,      27,      25],
       [    625,      64,    6561, 4782969],
       [     81,   16807,       4,       1]])

In [81]:
# numpy String Function

In [98]:
arr = np.array(["pw" ,"Skills"])


In [99]:
arr

array(['pw', 'Skills'], dtype='<U6')

In [100]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [101]:
np.char.lower(arr)

array(['pw', 'skills'], dtype='<U6')

In [102]:
np.char.upper(np.array(["Abhinesh"]))

array(['ABHINESH'], dtype='<U8')

In [103]:
np.char.lower(np.array(["Abhinesh"]))

array(['abhinesh'], dtype='<U8')

In [104]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [105]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [106]:
# Mathematical function

In [107]:
arr1

array([[2, 4, 3, 5],
       [5, 4, 9, 9],
       [3, 7, 2, 1]])

In [108]:
np.sin(arr1)

array([[ 0.90929743, -0.7568025 ,  0.14112001, -0.95892427],
       [-0.95892427, -0.7568025 ,  0.41211849,  0.41211849],
       [ 0.14112001,  0.6569866 ,  0.90929743,  0.84147098]])

In [109]:
np.cos(arr1)

array([[-0.41614684, -0.65364362, -0.9899925 ,  0.28366219],
       [ 0.28366219, -0.65364362, -0.91113026, -0.91113026],
       [-0.9899925 ,  0.75390225, -0.41614684,  0.54030231]])

In [110]:
np.tan(arr1)

array([[-2.18503986,  1.15782128, -0.14254654, -3.38051501],
       [-3.38051501,  1.15782128, -0.45231566, -0.45231566],
       [-0.14254654,  0.87144798, -2.18503986,  1.55740772]])

In [111]:
np.exp(arr1)

array([[7.38905610e+00, 5.45981500e+01, 2.00855369e+01, 1.48413159e+02],
       [1.48413159e+02, 5.45981500e+01, 8.10308393e+03, 8.10308393e+03],
       [2.00855369e+01, 1.09663316e+03, 7.38905610e+00, 2.71828183e+00]])

In [113]:
np.log10(arr1)

array([[0.30103   , 0.60205999, 0.47712125, 0.69897   ],
       [0.69897   , 0.60205999, 0.95424251, 0.95424251],
       [0.47712125, 0.84509804, 0.30103   , 0.        ]])

In [115]:
np.power(arr1 ,2)  # Square 

array([[ 4, 16,  9, 25],
       [25, 16, 81, 81],
       [ 9, 49,  4,  1]])

In [117]:
np.power(arr1 ,3) # cube 

array([[  8,  64,  27, 125],
       [125,  64, 729, 729],
       [ 27, 343,   8,   1]])

In [118]:
np.mean(arr1)

4.5

In [119]:
np.max(arr1)

9

In [122]:
np.std(arr1) # Standerd deviations 

2.533114025595111

In [124]:
np.var(arr1) # variance

6.416666666666667

In [125]:
np.add(arr1,arr2)

array([[11,  6,  6,  7],
       [ 9,  7, 13, 16],
       [ 7, 12,  4,  6]])

In [127]:
np.multiply(arr1,arr2)

array([[18,  8,  9, 10],
       [20, 12, 36, 63],
       [12, 35,  4,  5]])

In [129]:
np.mod(arr1,arr2)   # return Remainder 

array([[2, 0, 0, 1],
       [1, 1, 1, 2],
       [3, 2, 0, 1]])

In [130]:
# sort And Search

In [131]:
arr =np.array([5,6,2,1])

In [132]:
np.sort(arr)

array([1, 2, 5, 6])

In [138]:
arr4=np.random.randint(1,9,(3,3))

In [139]:
arr4

array([[5, 8, 6],
       [2, 1, 7],
       [5, 4, 7]])

In [140]:
np.sort(arr4)

array([[5, 6, 8],
       [1, 2, 7],
       [4, 5, 7]])

In [141]:
np.searchsorted(arr , 3)

4

In [142]:
arr

array([5, 6, 2, 1])

In [143]:
arr5 =np.random.randint(0,2,(3,3))

In [144]:
arr5

array([[1, 0, 1],
       [0, 1, 1],
       [0, 1, 0]])

In [145]:
np.count_nonzero(arr5)

5

In [149]:
arr5>0

array([[ True, False,  True],
       [False,  True,  True],
       [False,  True, False]])

In [151]:
np.where(arr>0)

(array([0, 1, 2, 3]),)

In [153]:
np.extract(arr1>0,arr1)

array([2, 4, 3, 5, 5, 4, 9, 9, 3, 7, 2, 1])

In [156]:
arr1

array([[2, 4, 3, 5],
       [5, 4, 9, 9],
       [3, 7, 2, 1]])

In [155]:
arr1.byteswap()

array([[144115188075855872, 288230376151711744, 216172782113783808,
        360287970189639680],
       [360287970189639680, 288230376151711744, 648518346341351424,
        648518346341351424],
       [216172782113783808, 504403158265495552, 144115188075855872,
         72057594037927936]])

In [173]:
import numpy.matlib as nm   # matlib -- is matrix  Library 

In [174]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [175]:
nm.zeros((3,4))

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [176]:
nm.ones(5)

matrix([[1., 1., 1., 1., 1.]])

In [177]:
nm.ones((4,5),int)

matrix([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [178]:
# Numpy Linear algebra 

In [186]:
ar1=np.random.randint(1,10 ,(3,3))
ar2=np.random.randint(1,10 ,(3,3))

In [187]:
ar1

array([[2, 5, 3],
       [9, 1, 2],
       [6, 3, 6]])

In [188]:
ar2

array([[6, 7, 3],
       [2, 9, 8],
       [1, 3, 5]])

In [191]:
ar1 @ ar2

array([[25, 68, 61],
       [58, 78, 45],
       [48, 87, 72]])

In [197]:
a=np.array([[7,5,-3],[3,-5,2],[5,3,-7]])

In [198]:
b=np.array([16,-8,0])

In [199]:
a

array([[ 7,  5, -3],
       [ 3, -5,  2],
       [ 5,  3, -7]])

In [200]:
b

array([16, -8,  0])

In [201]:
np.linalg.solve(a,b)

array([1., 3., 2.])

In [205]:
ar1=np.random.randint(1,9 ,(2,2))


In [210]:
ar1

array([[3, 7],
       [3, 8]])

In [211]:
np.linalg.det(ar1)

3.0000000000000004

In [212]:
np.linalg.inv(ar1)

array([[ 2.66666667, -2.33333333],
       [-1.        ,  1.        ]])